### ISSUE TITLE
Let's find Yury.

### ISSUE THREAD

**Issue by notarealdeveloper** [babel-publishing/manifolder#3]
Yury hasn't accepted his invitation yet. He should ceremonially close this issue once he gets here.

I'll venmo $5 to anyone who manages to get him here before Monday.[1]

[Footnote 1: No reason for urgency, but a bit of game dynamics is fun.]

**Comment by notarealdeveloper** [comment]
See also #4.

**Comment by yurykiselev** [comment]
accepted

**Comment by notarealdeveloper** [comment]
Yury I owe you $5.

**Comment by yurykiselev** [comment]
C'mon, definitely not!
